// USER CLICKED IOLET TO CREATE PATCH CABLE
export const ADD_PATCH_CABLE = "ADD_PATCH_CABLE";

// USER REMOVED PATCH CABLE
export const REMOVE_PATCH_CABLE = "REMOVE_PATCH_CABLE";

// USER CREATED BLANK OBJECT
export const ADD_OBJECT = "ADD_OBJECT";

// USER CONNECTED OBJECT TO ANOTHER OBJECT
export const NEW_CONNECTION = "NEW_CONNECTION";

// USER CHANGED OBJECT IN SOME WAY
export const UPDATE_OBJECT = "OBJECT_TYPE_CHANGED";

// USER DRAGGED AROUND OBJECT, NEED TO UPDATE EVERYTHING
export const OBJECT_DRAGGED = 'OBJECT_DRAGGED';

// USER EXPORTING CURRENT SESSION
export const EXPORT_STATE = 'EXPORT_STATE';

// OBJECT SENDING DATA TO ANOTHER OBJECT
export const SEND_OBJECT_DATA = 'SEND_OBJECT_DATA';

// USER CLICKED ON OBJECT OR SOMEWHERE ELSE AND A NEW OBJECT NEEDS TO BECOME THE SELECTED
export const SELECT_NEW_OBJECT = 'SELECT_NEW_OBJECT'

// USER DELETED OBJECT
export const DELETE_OBJECT = 'DELETE_OBJECT'

// APP SUCCESSFULLY CREATED NEEDED AUDIO NODE
export const DSP_CREATE_SUCCESS = 'DSP_CREATE_SUCCESS'

// CHANGE ATTRIBUTES OF ALREADY EXISTING OBJECT
export const CHANGE_ATTRIBUTES = 'CHANGE_ATTRIBUTES'

// OBJECT TYPE HAS CHANGED
export const UPDATE_OBJECT_TYPE = 'UPDATE_OBJECT_TYPE'

