// USER CLICKED IOLET TO CREATE PATCH CABLE
export const ADD_PATCH_CABLE = "ADD_PATCH_CABLE";

// USER CREATED BLANK OBJECT
export const ADD_OBJECT = "ADD_OBJECT";

// USER CONNECTED OBJECT TO ANOTHER OBJECT
export const NEW_CONNECTION = "NEW_CONNECTION";

// USER CHANGED OBJECT TYPE
export const OBJECT_TYPE_CHANGED = "OBJECT_TYPE_CHANGED";
